load start2.mat;

disp(sprintf(['Brain Machine Interface Lab Exercise Module\n\n' ...
	      'Andrew H. Fagg (fagg@ou.edu)\nDavid Goldberg\n' ...
	      'Symbiotic Computing Laboratory\n' ...
	      'School of Computer Science\nUniversity of Oklahoma\n\n' ...
	      'Monkey Data Collection and Analysis: Nicho Hatsopoulos ' ...
	      '(University of Chicago)\n' ...
	      'KINArm Dynamics Model: Greg Ojakangas (Drury University)\n'...
	      'Lee Miller (Northwestern University\n' ...
	      '\nSupported by NIH (NSO48845) and by the University of Oklahoma']));




