function newwindow (fig, type)

% Create a new window

global parms;


if(nargin < 1)
  fig = 1;
end;

if(nargin < 2)
  type = parms.fig.types{1};
end;


% Confirm that the type is valid
str = strmatch(type, parms.fig.types);
if(isempty(str))
    disp('Valid figure types include:');
      for j=1:length(parms.fig.types);
	    disp(['   ',  parms.fig.types{j}]);
      end;
        error('Please choose a valid type');
end;

figure(fig);

uicontrol('Style', 'pushbutton', ...
	  'String', '<-', ...
	  'units', 'normalized', ...
	  'Position', [.01, .925 .05 .05], ...
	  'Callback', ...
	  ['figure_left(', num2str(fig), ')']);

uicontrol('Style', 'pushbutton', ...
	  'String', '->', ...
	  'units', 'normalized', ...
	  'Position', [.11, .925 .05 .05], ...
	  'Callback', ...
	  ['figure_right(', num2str(fig), ')']);

uicontrol('Style', 'pushbutton', ...
	  'String', 'in', ...
	  'units', 'normalized', ...
	  'Position', [.06, .95 .05 .05], ...
	  'Callback', ...
	  ['figure_in(', num2str(fig), ')']);

uicontrol('Style', 'pushbutton', ...
	  'String', 'out', ...
	  'units', 'normalized', ...
	  'Position', [.06, .9 .05 .05], ...
	  'Callback', ...
	  ['figure_out(', num2str(fig), ')']);

uicontrol('Style', 'pushbutton', ...
	  'String', 'redraw', ...
	  'units', 'normalized', ...
	  'Position', [.2, .95 .1 .05], ...
	  'Callback', ...
	  ['figure_regen(', num2str(fig), ')']);

fparms.width = 256;
fparms.start = 1;
fparms.type = str;
set(gcf, 'UserData', fparms);

gen_figure(fparms);
